---
- hosts: all
  gather_facts: false
  vars_prompt:
     - name: DOMAIN
       prompt: Enter Domain Name(default:validate.edjx.network)
       private: no
     - name: username
       prompt: Enter edjconsole username
       private: no
     - name: password
       prompt: Enter password
  roles:
  - edjplaybooks
