---
- hosts: demo
  vars_prompt:
     - name: bootstrap
       prompt: Do you want to run with bootstrap? yes|no
     - name: DOMAIN
       prompt: Enter Domain Name(default:validate.edjx.network)
  roles:
  - edjplaybooks
  tasks:
    - debug:
        msg: Completed all tasks
