- name: node start
  become: yes
  become_user: edjruntime
  args:
     chdir: /home/edjruntime/.edjx
  shell: |
        sed -i '/^\s*$/d' runtime/.env
        edjx node start
  register: nodestart
- debug:
     msg: Edjruntime deployed successfully
